services:
  roach1:
    image: cockroachdb/cockroach:v26.2.3
    hostname: roach1
    command: >
      start
      --insecure
      --advertise-addr=roach1:26357
      --http-addr=roach1:8080
      --listen-addr=roach1:26357
      --sql-addr=roach1:26257
      --join=roach1:26357,roach2:26357,roach3:26357
    ports:
      - "26257:26257"
      - "8080:8080"
    volumes:
      - roach1:/cockroach/cockroach-data
    networks:
      - roachnet

  roach2:
    image: cockroachdb/cockroach:v26.2.3
    hostname: roach2
    command: >
      start
      --insecure
      --advertise-addr=roach2:26357
      --http-addr=roach2:8081
      --listen-addr=roach2:26357
      --sql-addr=roach2:26258
      --join=roach1:26357,roach2:26357,roach3:26357
    ports:
      - "26258:26258"
      - "8081:8081"
    volumes:
      - roach2:/cockroach/cockroach-data
    networks:
      - roachnet

  roach3:
    image: cockroachdb/cockroach:v26.2.3
    hostname: roach3
    command: >
      start
      --insecure
      --advertise-addr=roach3:26357
      --http-addr=roach3:8082
      --listen-addr=roach3:26357
      --sql-addr=roach3:26259
      --join=roach1:26357,roach2:26357,roach3:26357
    ports:
      - "26259:26259"
      - "8082:8082"
    volumes:
      - roach3:/cockroach/cockroach-data
    networks:
      - roachnet

  cockroach-init:
    image: cockroachdb/cockroach:v26.2.3
    command: init --insecure --host=roach1:26357
    depends_on:
      - roach1
      - roach2
      - roach3
    networks:
      - roachnet
    restart: "no"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      PORT: 8081
      DATABASE_URL: postgresql://root@roach1:26357/defaultdb?sslmode=disable
    ports:
      - "3001:8081"
    depends_on:
      - cockroach-init
    networks:
      - roachnet
    restart: on-failure

volumes:
  roach1:
    name: roach1
  roach2:
    name: roach2
  roach3:
    name: roach3

networks:
  roachnet:
    name: roachnet
    driver: bridge